from configs.ToURBAN import SOURCE_DATA_CONFIG, TARGET_DATA_CONFIG, EVAL_DATA_CONFIG, EVAL_DATA_RURAL_CONFIG, TEST_DATA_CONFIG, TEST_DATA_CONFIG_SOURCE, TARGET_SET, source_dir
from albumentations import HorizontalFlip, VerticalFlip, RandomRotate90, Normalize, RandomCrop, RandomScale
from albumentations import OneOf, Compose
import ever as er
MODEL = 'ResNet'


IGNORE_LABEL = -1
MOMENTUM = 0.9
NUM_CLASSES = 6

SAVE_PRED_EVERY = 1000
SNAPSHOT_DIR = './log/baseline/2urban'

#Hyper Paramters

WEIGHT_DECAY = 1e-5
LEARNING_RATE = 1e-3
NUM_STEPS = 30000
NUM_STEPS_STOP = 20000  # Use damping instead of early stopping
PREHEAT_STEPS = 0
POWER = 0.9
EVAL_EVERY=1000
TARGET_SET = TARGET_SET
SOURCE_DATA_CONFIG = SOURCE_DATA_CONFIG
TARGET_DATA_CONFIG=TARGET_DATA_CONFIG
EVAL_DATA_CONFIG=EVAL_DATA_CONFIG
TEST_DATA_CONFIG=TEST_DATA_CONFIG
TEST_DATA_CONFIG_SOURCE=TEST_DATA_CONFIG_SOURCE
